package br.com.enterprise.pytaco.util;

public enum PytacoRequestEnum {
    NONE,
    CRIAR_CONTA,
    LOGIN,
    CHECK_VERSION,
    GERA_CHAVE_SEGURANCA,
    LISTA_CLUBES,
    CRIAR_CLUBE,
    ASSOCIAR,
    ATUALIZA_PYTACOS,
    ALTERAR_SENHA,
    LEMBRAR_SENHA,
    CRIAR_AVISO,
    ALTERAR_AVISO,
    LISTA_AVISOS,
    EXCLUIR_AVISO,
    LISTA_MEMBROS,
    BUSCA_AGENTE,
    ACEITAR_MEMBROS,
    TORNAR_AGENTE,
    DESATIVAR_MEMBRO,
    ENVIAR_FICHAS,
    RETIRAR_FICHAS;
}
